spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_register
    username: root
    password: chicago123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


jwt:
  auth:
    app: Spring-Security-App
    secret_key: testkey#secret@12334
    expires_in: 3600